---
name: Sub-ArgShortcut
version: 1.01
author:
  - 'Aristotle Pagaltzis <pagaltzis@gmx.de>'
abstract: simplify writing functions that use default arguments
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
provides:
  Sub::ArgShortcut:
    file: lib/Sub/ArgShortcut.pm
    version: 1.01
  Sub::ArgShortcut::Attr:
    file: lib/Sub/ArgShortcut/Attr.pm
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
