---
abstract: 'simplify writing functions that use default arguments'
author:
  - 'Aristotle Pagaltzis <pagaltzis@gmx.de>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.030, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-ArgShortcut
requires:
  Attribute::Handlers: 0
  Carp: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://github.com/ap/Sub-ArgShortcut/issues
  homepage: http://github.com/ap/Sub-ArgShortcut
  repository: git://github.com/ap/Sub-ArgShortcut
version: 1.021
